// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shyjfqosuykacllmaolc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoeWpmcW9zdXlrYWNsbG1hb2xjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MjUxOTAsImV4cCI6MjA3MzAwMTE5MH0.mM9obj0rGcTjzMNhF8HZzy03JURAsH2iSz921Ydr1eQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});